added serial to parallel design
AmrEssamMahmoud/SerDes_GP_ICpedia pull request #1
Opened 2024-11-23 22:15 UTC by OmarSalah239

2024-11-23 22:16 UTC, OmarSalah239 commented
added serial to parallel design

2024-11-24 13:31 UTC, balbal1 requested changes
good job👍 , did you test your code tho? always try making a small tb to check your designs quickly even if there is someone who will make the verification.

2024-11-24 13:31 UTC, balbal1 commented on hdl/tx/P2S.v
> +        if (bit_count == 0) begin
The last bit should get send when `bit_count` is 0, but this will not work because it will go inside this if condition.
You can fix this by starting the `bit_count` on 10

2024-11-24 13:31 UTC, balbal1 commented on hdl/tx/P2S.v
> +        serial_out<=temp_reg[9];
Serialization is usually done starting from LSB to the MSB, so you can make the `serial_out` take the `temp_reg[0]` and shift the `temp_reg` to the right.
(you can use shift operator `>>` instead of concatination)

2024-11-24 13:41 UTC, balbal1 requested changes

2024-11-24 13:41 UTC, balbal1 commented on hdl/tx/P2S.v
> +        end
The last bit should get send when `bit_count` is 0, but this will not work because it will go inside this if condition.
You can fix this by starting the `bit_count` on 10

2024-11-24 13:41 UTC, balbal1 commented on hdl/tx/P2S.v
> +        end
Serialization is usually done starting from LSB to the MSB, so you can make the `serial_out` take the `temp_reg[0]` and shift the `temp_reg` to the right.
(you can use shift operator `>>` instead of concatenation)

2024-11-24 13:55 UTC, OmarSalah239 commented on hdl/tx/P2S.v
> +        end
that's my mistake. You are correct, I will fix it.
thanks, Ali.

2024-11-24 16:54 UTC, balbal1 requested changes
Nicely done 👏🏻
You may also upload the tb you created inside `hdl/tx/tb` folder and name it `P2S_tb.v` for convention.

2024-11-24 16:54 UTC, balbal1 commented on hdl/tx/P2S.v
> +  output reg serial_out
You are free to name the internals signals as you want but the interface signals should be named according to a convention. So please change the names according to this diagram.
`parallel_in` -> `TxParallel_10`
`clk` -> `BitCLK`
`reset_n` -> `Reset`
`serial_out` -> `Serial`
![image](https://github.com/user-attachments/assets/a591bcbb-24d7-44aa-aad6-168bda435510)

2024-11-24 16:54 UTC, balbal1 commented on hdl/tx/P2S.v
> +      serial_out<=temp_reg[1]; // this is done because we took the first bit (LSB) in the previous clk cycle
You can write the `serial_out` line outside the if condition entirely to avoid duplicating the line to the two cases

2024-11-24 20:50 UTC, balbal1 approved these changes
Nice job, all is good ❤

2024-11-24 22:26 UTC, AmrEssamMahmoud approved these changes
very good job omar <3 
 ps : need to ask doctor about a if there a valid signal for data

2024-11-24 22:26 UTC, merged