KWU
AmrEssamMahmoud/SerDes_GP_ICpedia pull request #5
Opened 2024-11-24 15:31 UTC by KarimWalidFawzy

2024-11-24 16:41 UTC, balbal1 requested changes
Good job 👍. Also same as Omar, always check your design with a small tb before uploading even if there is someone who will bake the verification.
Also change the location of the file from `blocks/tx/` to `hdl/rx`

2024-11-24 16:41 UTC, balbal1 commented on blocks/tx/ser_to_parallel.v
> +                TR[1]<=ip;
The cases starting from `1'hA` to `1'hF` should not be possible to happen, so remove them and put a `default` case instead.

2024-11-24 16:41 UTC, balbal1 commented on blocks/tx/ser_to_parallel.v
> +                count<=count+1;
Here the count loops from 6 to 16, which makes the bits order wrong when deserialized.
The count also should loop from `0` to `9`, so the condition should be
```
if (count == 1'h9)
    count <= 1'h0;
```

2024-11-24 16:41 UTC, balbal1 commented on blocks/tx/ser_to_parallel.v
> +    input ip);
You are free to name the internals signals as you want but the interface signals should be named according to a convention. So please change the names according to this diagram.
`clk` -> `BitCLK`
`rst` -> `Reset`
`op` -> `RxParallel_10`
`ip` -> `Serial`
![image](https://github.com/user-attachments/assets/a591bcbb-24d7-44aa-aad6-168bda435510)

2024-11-25 22:09 UTC, balbal1 approved these changes
Good job 👏🏻

2024-11-26 21:04 UTC, OmarSalah239 approved these changes

2024-11-26 21:05 UTC, merged